# Migration Factory Installation

The Migration Factory is a set of Ansible based tooling, powered by Ansible Automation Platform (AAP), that simplifies the use of OpenShift Virtualization and focuses on three (3) primary areas:

. Analyzing existing environments
. Migration of Virtual Machines into OpenShift Virtualization
. Day 2 Operations

This section describes the process for setting up the Migration Factory within the OpenShift environment.

To get started, you will need the following:

. Container runtime, such as link:https://podman.io[Podman]
. Red Hat Customer Portal / Red Hat Developer Subscription account
. Automation Hub Token

In addition, the following will be provided for you
. Credentials to retrieve the Migration Factory Ansible Execution Environment
. Credentials to retrieve the Migration Factory Ansible Content Collection from Git

The process of deploying the Migration Factory makes use of Ansible on the local machine to prepare an instance of Ansible Automation Platform for use managing the lifecycle of Virtual Machines and OpenShift Virtualization. While several architectural patterns are available for deploying the Migration Factory, including configuring an existing instanceof Ansible Automation Platform, you will use the tooling provided with the Migration Factory to deploy a new instance of Ansible Automation Platform to your OpenShift environment.

Utilize the following sections to deploy the Migration Factory by first installing any prerequisite software necessary on your machine and then to configure the Migration Factory for use in your own environment.

## Local Machine Configuration

Since Ansible is used to facilitate the deployment of the Migration Factory, you will need to have the required tooling installed and configured on your Machine.

### Ansible Navigator

link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_content_navigator/index[Ansible Navigator] is to used execute the Ansible automation as it simplifies how Ansible content is managed and used by leveraging Execution Environments which are container images which include all of the necessary dependencies and tools needed.

Install Ansible Navigator by first creating a new Python Virtual Environment called `etx` within the `~/.virtualenvs` directory

[source,shell]
----
mkdir -p ~/.virtualenvs/
python -m venv ~/.virtualenvs/etx
----

[NOTE]
====
You may choose an alternate location to store your Python Virtual Environment, if desired.
====

Source the newly created Virtual Environment

[source,shell]
----
source ~/.virtualenvs/etx/bin/activate
----

Once a Virtual Environment has been activated, the shell prompt will show the name of the active Virtual Environment; in this case `(etx)`

The Migration Factory includes an Execution Environment to support executing Ansible Automation both locally and within Ansible Automation Platform. Since an Execution Environment runs as a container image, you will need to have a container runtime, such as Podman installed and configured on your machine. Consult the link:https://podman.io[Podman website] for the steps necessary to complete the installation.

The Execution Environment supporting the Migration Factory is located within a private Container registry. As as a result, you will need to provide credentials in order to obtain the image. Using the credentials provided, login to the remote registry:

[source,shell]
----
podman login quay.io/redhat-cop
----

Pull the Execution Environment to your local machine

[source,shell]
----
podman pull quay.io/redhat-cop/virt-migration-factory-ee:latest
----

### Source Code

Source code, including Automation tooling (playbooks, collections, etc) for the Migration Factory are located within a protected Git repository within the link:https://gitlab.consulting.redhat.com[Red Hat Consulting GitLab instance] and the link:https://gitlab.consulting.redhat.com/redhat-cop/vmware-openshift-virt-migration[vmware-openshift-virt-migration group].

Clone the Migration Factory Collection (`infra.virt_migration_factory`) source code to your local machine and change into the cloned directory. When prompted, enter the Git username and password that was provided previously:

[source,shell]
----
git clone https://gitlab.consulting.redhat.com/redhat-cop/vmware-openshift-virt-migration/virt_migration_factory.git
cd virt_migration_factory
----

## Building your Ansible Inventory

The core component for setting up the Migration Factory is the link:https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html[Ansible Inventory] as it defines both the composition of the OpenShift environment, but also properties to enable Ansible Automation Platform to manage all of the resources effectively.

Given that the Migration Factory relies heavily on the Inventory, there are a number of variables that can be configured. An inventory starter (in YAML format) is located in the `ansible/migration-factory/inventory-etx.yml` file within the ETX workshop Git repository. Copy the file from the ETX repository to the root of the cloned Migration Git repository.

Open the `inventory-etx.yml` file that has been copied to the root of the Migration Factory Git repository. The inventory starter includes a lot of comments in order to illustrate the significance of each value and to ensure the proper configurations are set.

At a high level, the inventory is organized similar to the following:

[source,yaml]
----
# Migration Factory Inventory
all:
  vars:
    # Common variables applied to all inventory groups
    my_var: 'my_var_value'

# Migration Factory Hub Clusters
migration_factory_hub:
  hosts:
    hub-cluster:
      # Variables to apply to specific Migration Factory Hub Cluster
      my_var: 'my_var_value'

  # Variables to apply to all Migration Factory Hub Clusters  
  vars:
    my_var: 'my_var_value'

# Migration Factory Spoke Clusters
migration_factory_spoke:
  hosts:
    spoke-cluster:
      # Variables to apply to specific Migration Factory Splme Cluster
      my_var: 'my_var_value'
  
  # Variables to apply to all Migration Factory Spoke Clusters  
  vars:
    my_var: 'my_var_value'

    # Defines a set of source and destination environments which are turned into MTV providers
    migration_targets:
      - name: my-vmware-cluster
        type: vmware
        host: vcenter.example.com
        # ...

# Standalone Ansible Automation Platform Environments
migration_factory_aap:
  hosts:
    aap_host:
      # Ansible Automation Platform Variables
      controller_host: aap.example.com
      controller_token: changeme
      controller_validate_certs: true
----

The Migration Factory supports multiple deployment patterns and these can be modeled (as seen above) within the inventory. Three Inventory groups are available and described in the following table:

[cols="1,1"]
|===
|Group Name|Description

| `migration_factory_hub`
| Hub OpenShift clusters

| `migration_factory_spoke`
| Spoke OpenShift clusters

| `migration_factory_aap`
| Standalone Ansible Automation Platform environments
|===

In addition, _Migration Targets_ represent source and destination environments containing Virtual Machines. In most cases, a VMware vSphere environment will be a source and an OpenShift cluster will be a destination. Migration Targets are defined within the `migration_factory_spoke` Inventory group using the `migration_targets` variable.

For this workshop, since there is only 1 OpenShift cluster, we will leverage a combined hub and spoke architecture within the same cluster. The Migration Factory will also be responsible for deploying and configuring Ansible Automation Platform on the hub instance.

Update the Inventory as described in the following sections.

### General Variables

There are a set of variables that are used throughout the automation and are found within `all` inventory group.

Set the `rh_username` and `rh_password` properties with your Red Hat Customer Portal or Developer account as shown below:

[source,yaml]
----
rh_username: <username>
rh_password: <password>
----

To obtain the Migration Factory Ansible Execution Environment, set the `container_username` and `container_password` properties using the provided credentials.

[source,yaml]
----
container_username: <username>
container_password: <password>
----

An Ansible Controller _Project_ will be configured to source the baseline set of Ansible automation so that it can be managed by the platform. Set the `git_username` and `git_password` properties using the provided credentials.

[source,yaml]
----
git_username: <username>
git_password: <password>
----

Set the Ansible Automation Hub token sourced previously within the `automation_hub_token` property.

[source,yaml]
----
automation_hub_token: <token>
----

OpenShift connectivity details can be specified at a host level, enabling an Inventory to contain connectivity details for multiple cluster. The following properties can be used to specify how the Migration Factory connects to each cluster.

[source,yaml]
----
# Variables that can be used to specify how to connect to an OpenShift environment
openshift_host: # OpenShift API Server Address (Example: https://api.example.com:6443)
openshift_verify_ssl: # Perform SSL Verification

# OpenShift Authentication Options. Specify a username/password or API key
openshift_username: # OpenShift User
openshift_password: # OpenShift Password
openshift_temporary_api_key: # Temporary API Key which is used to create an SA and Secret
openshift_api_key: # Long lived SA API Key
----

Since there is only 1 cluster being configured, the `openshift_host` and `openshift_temporary_api_key` will be provided at runtime by specifying an extra variable with details from the active OpenShift CLI session.

### Migration Targets

Within the `vars` section of the `migration_factory_spoke` Inventory group, we will configure how the Migration Factory manages the VMware environment. Set the `host`, `username` and `password` properties with the details of your VMware environment as shown below:

[source,yaml]
----
migration_factory_spoke:
  vars:
    migration_targets:
    - name: vmware-etx
      type: vmware
      host: <hostname>
      username: <username>
      password: <password>
----

### Further Customization

For the sake of time, we only covered the most important properties that are needed to set up the Migration Factory. Some of the additional variables that can be customized are included within the Inventory file already. For example, the `aap_namespace` property is used to specify the OpenShift namespace where Ansible Automaton Platform will be installed:

[source,yaml]
----
aap_namespace: migration-factory
----

## Provision the Migration Factory

The installation of the Migration Factory within the OpenShift workshop environment involves the deployment and configuration of Ansible Automation Platform.

Navigate to the root of the cloned Migration Factory Collection and deploy the Migration Factory to the OpenShift environment.

[IMPORTANT]
====
Ensure that your OpenShift CLI has a valid and active session to the OpenShift cluster. Otherwise, failures will occur.
====

[source,shell]
----
ansible-navigator run \
  --pp=missing \
  --eei=quay.io/redhat-cop/virt-migration-factory-ee:latest \
  -m stdout \
  --eev=$(pwd):/runner/project:Z \
  playbooks/migration_factory_aap.yml \
  -i inventory-etx.yml \
  --pae false \
  -e openshift_host=$(oc whoami --show-server) \
  -e openshift_temporary_api_key=$(oc whoami -t)
----

The provisioning will take a few minutes to complete as OpenShift is populated with Migration Factory resources.

## Verify the Provisioning

Once the playbook associated with the provisioning of the Migration Factory has completed successfully, perform te following steps to confirm Ansible Automation Platform is available within the OpenShift cluster and it has been configured properly.

Launch a web browser and navigate to the OpenShift Web Console.

Verify a new project called `migration-factory` has been created by expanding the *Home* section on the left hand navigation bar and selecting *Projects*.

Confirm *migration-factory* is present and select the hyperlink under the _Name_ column.

Once in the _migration-factory_ project, select *Operators* from the left hand navigation bar and select *Installed Operators*.

Select the *Ansible Automation Platform* to view details related to the Operator.

Select the *Ansible Automation Platform* tab to list all of the Ansible Automation Platform instances in the _migration-factory_ Project.

Select the *aap-etx* instance to view details related to the instance that was provisioned.

Under _Gateway Admin Password_, select the  *aap-etx-admin-password* Secret which contains the credentials to authenticate to Ansible Automation Platform.

On the _aap-etx-admin-password_ Secret page, click the *Reveal values* link associated with the _password_ property and copy the value so that it can be used to authenticate to Ansible automation Platform.

Go back to the _aap-etx_ AnsibleAutomationPlatform_ instance and navigate to Ansible Automation Platform by selecting the link underneath _URL_.

Login using *admin* as the username and paste the password copied using the value obtained from the _aap-etx-admin-password_ Secret.

### Exploring Ansible Automation Platform

Once authenticated to Ansible Automation Platform, let's take a moment to explore the Migration Factory related content that was populate within the instance. First, the same Ansible Execution Environment that was used to facilitate the deployment of the Migration has been added and will be used to run Migration Factory related automation within the platform. This can be verified by expanding the _Automation Execution_ section on the left hand navigation bar, expand _Infrastructure_, and then select *Execution Environments*. Not surprisingly, _Migration Factory_ is the name of the Execution Environment that was added to the platform.

Next, an Organization called *MTV* was created to contain all of the resources related to the Migration Factory. This can be seen by expanding the _Access Management_ section on the left hand navigation bar and selecting *Organizations*. The credentials associated with Red Hat Automation Hub token provided earlier were added to the Organization so that any certified and validated content that is needed can be retrieved.

In addition to the Credential associated with Red Hat Automation Hub, a set of other credentials were populated and can be seen by expanding the _Automation Execution_ section on the left hand navigation bar, expand _Infrastructure_, and selecting *Credentials*. Some of these credentials makes use of custom _Credential Types_ which can be seen by selecting *Credential Types* right below _Credentials_ on the left hand navigation bar.

The primary set of content (playbooks) responsible for execution is source from the aforementioned GitLab instance and is brought into Ansible Controller as a Project called _Migration_. This can be seen by selecting *Projects* under the _Automation Execution_ section on the left hand navigation bar.

Finally, view all of the Migration Factory related _Job Templates_ and _Workflow Job Templates_ by selecting *Templates* under the _Automation Execution_ section on the left hand navigation bar. We will be leveraging these resources in the upcoming section to support automating the migration of Virtual Machines into OpenShift.
